#!/bin/sh
# collection of functions that i use daily on my desktop
# I usally echo ". \"$HOME/opt/perso/bin/sh_functions\"" >> ~/.profile
# on my machines

# Prints ${$1}
# @1 variable name for which to get its value
varpt()
{
    local v="\$$1"
    eval "printf '%s' $v"
}

# Add an element to the tail of a variable
# @1 Variable name
# @2 new element
# @3 separator
add_tail()
{
    local old="$(printf "%s" "$(varpt "$1")")"
    local new="$(printf "%s" "$old" | sed -e "s,$2[$3]*,," -e "s,^$3,," -e "s,$3\$,,")"
    if [ -n "$new" ] ; then
        new="$new$3"
    fi
    eval "$1=\"$new$2\""
}

# Add an element to the head of a variable
# @1 Variable name
# @2 new element
# @3 separator
add_head()
{
    local old="$(printf "%s" "$(varpt "$1")")"
    local new="$(printf "%s" "$old" | sed -e "s,$2[$3]*,," -e "s,^$3,," -e "s,$3\$,,")"
    if [ -n "$new" ] ; then
        new="$3$new"
    fi
    eval "$1=\"$2$new\""
}

# Sets up my personal environment
#
# I like to compile beelding edge stuff and install it in my user
# account so i don't pollute the system. Hence this very lenghty
# function that takes care to let gcc/g++/man/pkg-config/ld still
# find those softwares when needed
env_personal()
{
    PANO_HOME="${HOME}/opt/hugin"
    VIDEO_HOME="${HOME}/opt/video"
    PERSO_HOME="${HOME}/opt/perso"
    DT_HOME="${HOME}/opt/darktable"
    PHOTO_HOME="${HOME}/opt/photolibs"

    #------------------------------------------------------------
    #    PATH
    #------------------------------------------------------------

    add_tail "PATH" "${PERSO_HOME}/bin" ":"
    add_head "PATH" "${PANO_HOME}/bin" ":"
    add_head "PATH" "${VIDEO_HOME}/bin" ":"
    add_tail "PATH" "${DT_HOME}/bin" ":"

    #------------------------------------------------------------
    # MANPATH
    #------------------------------------------------------------

    add_tail "MANPATH" "${PANO_HOME}/share/man" ":"
    add_tail "MANPATH" "${VIDEO_HOME}/share/man" ":"
    MANPATH=":$MANPATH"

    #------------------------------------------------------------
    # LD_LIBRARY_PATH
    #------------------------------------------------------------

    add_head "LD_LIBRARY_PATH" "${PANO_HOME}/lib" ":"
    add_head "LIBRARY_PATH" "${PANO_HOME}/lib" ":"
    add_head "LD_LIBRARY_PATH" "${VIDEO_HOME}/lib" ":"
    add_head "LIBRARY_PATH" "${VIDEO_HOME}/lib" ":"
    add_head "LD_LIBRARY_PATH" "${PHOTO_HOME}/lib" ":"
    add_head "LIBRARY_PATH" "${PHOTO_HOME}/lib" ":"

    #------------------------------------------------------------
    # Include dirs for C language 
    #------------------------------------------------------------

    add_head "CPATH" "${PANO_HOME}/include" ":"
    add_head "CPATH" "${VIDEO_HOME}/include" ":"
    add_head "CPATH" "${PHOTO_HOME}/include" ":"

    #------------------------------------------------------------
    # Python path
    #------------------------------------------------------------

    #add_tail "PYTHONPATH" "${MERCURIAL_HOME}/lib/python" ":"

    #------------------------------------------------------------
    # Pkg config path
    #------------------------------------------------------------

    add_tail "PKG_CONFIG_PATH" "${PANO_HOME}/lib/pkgconfig" ":"
    add_tail "PKG_CONFIG_PATH" "${VIDEO_HOME}/lib/pkgconfig" ":"
    add_tail "PKG_CONFIG_PATH" "${PHOTO_HOME}/lib/pkgconfig" ":"

    #------------------------------------------------------------
    # Shell prompt
    #------------------------------------------------------------

    PS1='\[\e[01;34m\][\u@\h${debian_chroot:+($debian_chroot)}:\W]\$\[\e[0m\] '
    alias darktablet="darktable --library :memory:"

    #------------------------------------------------------------
    # Finalization
    #------------------------------------------------------------

    export PATH
    export MANPATH
    export LD_LIBRARY_PATH
    export LIBRARY_PATH
    export PKG_CONFIG_PATH
    export CPATH
    export PYTHONPATH
    export DT_HOME
}

# Returns the numbr of CPUs on Linux i386/x86_64
numcpu()
{
    grep ^processor /proc/cpuinfo | wc -l
}

# enable/disable nouveau in a nasty way
# @1 on/enable/off/disable
# @2 kernel revision (optional, uses current running revision)
nouveau_setup()
{
    if [ $# -eq 1 ] ; then
        revision="$(uname -r)"
    else
        revision="$2"
    fi

    local nvdir="/lib/modules/$revision/kernel/drivers/gpu/drm/nouveau"
    local nvenabled="$nvdir/nouveau.ko"
    local nvdisabled="$nvdir/nouveau.ko.disabled"

    case "$1" in
    on|enable)
        moved="$nvenabled"
        checked="$nvdisabled"
        ;;
    off|disable)
        checked="$nvenabled"
        moved="$nvdisabled"
        ;;
    *)
        printf '%s <enable|disable|on|off> [kernel revision]\n' "$0"
        return 1
    esac

    if [ -f "$checked" ] ; then
        sudo mv "$checked" "$moved"
    fi

    return 0
}

env_personal
